In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.arange(3, 20, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
np.random.rand(5)

array([0.56763679, 0.59153509, 0.90567202, 0.02967811, 0.08465738])

In [8]:
np.random.rand(3,4)

array([[0.33097597, 0.5471079 , 0.6791497 , 0.00627584],
       [0.68397776, 0.42329505, 0.98917299, 0.33541186],
       [0.08100792, 0.91071955, 0.58063562, 0.6017533 ]])

In [9]:
np.random.randn(3)

array([ 0.26830567, -0.46475294, -1.32599032])

In [10]:
np.random.randn(3,3)

array([[ 0.85521647,  1.07922309, -0.82103461],
       [ 1.40553936, -0.02680402,  2.85972235],
       [-0.15623765, -0.37538539,  0.59525918]])

In [19]:
np.random.randint(1)

0

In [22]:
ranarr = np.random.randint(1, 50, 25)

In [36]:
ranarr = ranarr.reshape(5,5)

In [37]:
ranarr.max()

48

In [38]:
ranarr.min()

1

In [39]:
ranarr.argmax()

17

In [40]:
ranarr.argmin()

0

In [41]:
ranarr.shape

(5, 5)

In [42]:
ranarr.dtype

dtype('int32')

In [45]:
arr = np.arange(0, 20, 1)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
arr2 = arr

In [48]:
arr2[1] = 939

In [49]:
arr

array([  0, 939,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [50]:
arr2 = arr.copy()

In [51]:
arr2[0] = 93

In [52]:
arr

array([  0, 939,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [53]:
arr2

array([ 93, 939,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [54]:
 arr = np.array([[2,3,5],[2,6,6],[7,0,8]])

In [55]:
arr

array([[2, 3, 5],
       [2, 6, 6],
       [7, 0, 8]])

In [56]:
arr.shape

(3, 3)

In [62]:
arr[1:,1:]

array([[6, 6],
       [0, 8]])

In [63]:
arr>3

array([[False, False,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [64]:
bool_arr = arr>3

In [66]:
arr[bool_arr]

array([5, 6, 6, 7, 8])

array([[ 0.90929743,  0.14112001, -0.95892427],
       [ 0.90929743, -0.2794155 , -0.2794155 ],
       [ 0.6569866 ,  0.        ,  0.98935825]])